# Generated by Django 3.2.9 on 2021-12-30 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_examdetails_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='totaltime',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 30)),
        ),
    ]
