# Generated by Django 3.2.9 on 2021-12-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_rel_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(unique=True)),
                ('year', models.CharField(default='FE', max_length=5)),
                ('stream', models.CharField(default='None', max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('rel_key', models.EmailField(default='1111@gmail.com', max_length=254, verbose_name='email address')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
