# Generated by Django 3.2.9 on 2021-12-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tempuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
