# Generated by Django 3.2.9 on 2021-12-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_tempuser_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
