# Generated by Django 3.2.9 on 2022-01-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_tempuser_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='FE', max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.CharField(max_length=150, unique=True)),
                ('contact', models.IntegerField(default=0)),
            ],
        ),
    ]
